name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '^3.10'
        architecture: x64
    - run: pip install nox==2022.8.7
    - run: pip install nox-poetry==1.0.1
    - run: pip install poetry==1.2.1
      # Run our tests then generate a coverage report
    - run: nox --sessions tests-3.10 coverage
      # Upload coverage report to codecov
    - uses: codecov/codecov-action@v3
      if: success() || failure()
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        name: codecov-umbrella
        fail_ci_if_error: true
        file: coverage.xml
